---
title: "Drift, selection, change, and shift"
author: "Workshop @ Evolang 2020"
output: html_document
---


## Workshop description
 
Language change, like other evolutionary processes, involves both directed selection as well as stochastic drift (Sapir 1921; Jespersen 1922; Andersen 1987; McMahon 1994; Croft 2000; Baxter et al. 2006; Van de Velde 2014; Steels & Szathmáry 2018).

Selective advantage of a variant may rise from various sources, such as sociolinguistic prestige of competing variants (Labov 2011; Hernández-Campoy & Conde-Silvestre 2012), culture-specific communicative need (Regier et al. 2016, Gibson et al. 2017, Karjus et al. to appear), dissemination across domains (Altmann et al. 2011; Stewart & Eisenstein 2018), momentum (Stadler et al. 2016), conscious language planning actions (Ghanbarnejad et al. 2014; Daoust 2017), an interplay of exogenous and endogenous factors (Cuskley et al. 2014), cognitive biases (Smith et al. 2013; Winter & Wedel 2016; Culbertson 2017) or simply the form of a variant in terms of length (Zipf 1949; Kanwal et al. 2017) and iconicity (Dingemanse et al. 2015). Additionally, various usage and acquisition properties have been shown to predictors of success (Kershaw et al. 2016; Calude et al. 2017; Grieve 2018; Roberts & Monaghan 2019; Turney et al. 2019).

Competition may be viewed as operating within but also between languages, the former leading to the replacement of communicative variants, the latter to the extinction of entire languages. Signatures of innovation, selection and competition should be inferable from the usage statistics alone, given adequately large and representative diachronic data. This is an idea that has been explored in the domain of language change (Reali & Griffiths 2010; Blythe 2012; Sindi & Dale 2016; Newberry et al. 2017; Amato et al. 2018; Grieve et al. 2018), cultural evolution (Hahn & Bentley 2003; Kandler & Crema 2019) as well as inter-language competition (Abrams & Strogatz 2003; Zhang & Gong 2013; Kandler & Steele 2017). Selection for communicative variants and languages to use takes place on the level of the individual, but historical data often consists of only imperfect aggregate samples from the population, presenting problems for inference (Pechenick et al. 2015; de Smet 2016; Fonteyn 2017; Petré & Van de Velde 2018; Kandler et al. 2017).

These topics are highly interrelated, but the research is spread across multiple disciplines including linguistics, biology, physics, mathematics and computer science. The goal of this workshop is to bring together researchers working on various aspects of these issues, including the interplay of drift and selection in language change, success of innovations and borrowings, and competition dynamics both within and between languages. We welcome contributions dealing with (but not limited to) methods of identifying these processes, issues regarding data (corpora, censuses, surveys, assemblages, etc.), empirical investigations as well as modelling results.

## Organizers

Andres Karjus (University of Edinburgh)<br>
Jack Grieve (University of Birmingham)<br>
Anne Kandler (Max Planck Institute for Evolutionary Anthropology)

## Call for papers

### Timeline
 
---

### References

<font size="1">
Abrams, D. M., & Strogatz, S. H. (2003). Modelling the dynamics of language death. Nature, 424, 900.<br>
Altmann, E. G., Pierrehumbert, J. B., & Motter, A. E. (2011). Niche as a Determinant of Word Fate in Online Groups. PLOS ONE, 6(5), 1–12.<br>
Amato, R., Lacasa, L., Díaz-Guilera, A., & Baronchelli, A. (2018). The dynamics of norm change in the cultural evolution of language. Proceedings of the National Academy of Sciences.<br>
Andersen, H. (1987). The structure of drift. Historical Linguistics, 1–20.<br>
Baxter, G. J., Blythe, R. A., Croft, W., & McKane, A. J. (2006). Utterance selection model of language change. Phys. Rev. E, 73(4), 046118.<br>
Blythe, R. A. (2012). Neutral evolution: A null model for language dynamics. Advances in Complex Systems, 15(3–4).<br>
Calude, A. S., Miller, S., & Pagel, M. (2017). Modelling loanword success – a sociolinguistic quantitative study of Māori loanwords in New Zealand English. Corpus Linguistics and Linguistic Theory, 0(0).<br>
Croft, W. (2000). Explaining Language Change: An Evolutionary Approach. Longman.<br>
Culbertson, J. (2017). New approaches to Greenbergian word order dependencies. In Studies in Diversity Linguistics. Dependencies in Language: On the Causal Ontology of Linguistic Systems (pp. 23–38). Language Science Press.<br>
Cuskley, C. F., Pugliese, M., Castellano, C., Colaiori, F., Loreto, V., & Tria, F. (2014). Internal and External Dynamics in Language: Evidence from Verb Regularity in a Historical Corpus of English. PLOS ONE, 9(8), 1–7.<br>
Daoust, D. (2017). Language Planning and Language Reform. In The Handbook of Sociolinguistics (pp. 436–452).<br>
De Smet, H. (2016). How gradual change progresses: The interaction between convention and innovation. Language Variation and Change, 28(1), 83–102.<br>
Dingemanse, M., Blasi, D. E., Lupyan, G., Christiansen, M. H., & Monaghan, P. (2015). Arbitrariness, Iconicity, and Systematicity in Language. Trends in Cognitive Sciences, 19(10), 603–615.<br>
Fonteyn, L. (2017). The aggregate and the individual: thoughts on what non-alternating authors reveal about linguistic alternations – a response to Petré. English Language and Linguistics, 21(2), 251–262.<br>
Ghanbarnejad, F., Gerlach, M., Miotto, J. M., & Altmann, E. G. (2014). Extracting information from S-curves of language change. Journal of The Royal Society Interface, 11(101).<br>
Gibson, E., Futrell, R., Jara-Ettinger, J., Mahowald, K., Bergen, L., Ratnasingam, S., Conway, B. R. (2017). Color naming across languages reflects color use. Proceedings of the National Academy of Sciences.<br>
Grieve, J. (2018). Natural selection in the modern english lexicon. In C. Cuskley, M. Flaherty, H. Little, L. McCrohon, A. Ravignani, & T. Verhoef (Eds.), The Evolution of Language: Proceedings of the 12th International Conference (EVOLANGXII).<br>
Grieve, J., Nini, A., & Guo, D. (2018). Mapping lexical innovation on American social media. Journal of English Linguistics, 46(4), 293–319. <br>
Hahn, M. W., & Bentley, R. A. (2003). Drift as a mechanism for cultural change: an example from baby names. Proceedings of the Royal Society of London B: Biological Sciences, 270(Suppl 1), S120–S123.<br>
Hernández-Campoy, J. M., & Conde-Silvestre, J. C. (2012). The handbook of historical sociolinguistics. John Wiley & Sons.<br>
Jespersen, O. (1922). Language, its nature, development, and origin. H. Holt.<br>
Kandler, A., & Crema, E. R. (2019). Analysing Cultural Frequency Data: Neutral Theory and Beyond. In A. M. Prentiss (Ed.), Handbook of Evolutionary Research in Archaeology (pp. 83–108).<br>
Kandler, A., Unger, R., & Steele, J. (2010). Language shift, bilingualism and the future of Britain’s Celtic languages. Philosophical Transactions of the Royal Society B: Biological Sciences, 365(1559), 3855–3864.<br>
Kandler, A., Wilder, B., & Fortunato, L. (2017). Inferring individual-level processes from population-level patterns in cultural evolution. Royal Society Open Science, 4(9).<br>
Kanwal, J., Smith, K., Culbertson, J., & Kirby, S. (2017). Zipf’s Law of Abbreviation and the Principle of Least Effort: Language users optimise a miniature lexicon for efficient communication. Cognition, 165, 45–52.<br>
Karjus, A., Blythe, R. A., Kirby, S., & Smith, K. (to appear). Quantifying the dynamics of topical fluctuations in language. Language Dynamics and Change<br>
Kershaw, D., Rowe, M., & Stacey, P. (2016). Towards Modelling Language Innovation Acceptance in Online Social Networks. Proceedings of the Ninth ACM International Conference on Web Search and Data Mining, 553–562.<br>
Labov, W. (2011). Principles of Linguistic Change, Volume 3: Cognitive and Cultural Factors.<br>
McMahon, A. M. S. (1994). Understanding Language Change. Cambridge University Press.<br>
Monaghan, P., & Roberts, S. G. (2019). Cognitive influences in language evolution: Psycholinguistic predictors of loan word borrowing. Cognition, 186, 147–158.<br>
Newberry, M. G., Ahern, C. A., Clark, R., & Plotkin, J. B. (2017). Detecting evolutionary forces in language change. Nature, 551(7679), 223.<br>
Pechenick, E. A., Danforth, C. M., & Dodds, P. S. (2015). Characterizing the Google Books Corpus: Strong Limits to Inferences of Socio-Cultural and Linguistic Evolution. PLoS ONE, 10(10), e0137041.<br>
Petré, P., & Van de Velde, F. (2018). The real-time dynamics of the individual and the community in grammaticalization. Language, 94(4), 867–901.<br>
Reali, F., & Griffiths, T. L. (2010). Words as alleles: connecting language evolution with Bayesian learners to models of genetic drift. Proceedings of the Royal Society B: Biological Sciences, 277(1680), 429–436.<br>
Regier, T., Carstensen, A., & Kemp, C. (2016). Languages Support Efficient Communication about the Environment: Words for Snow Revisited. PLOS ONE, 11(4), 1–17.<br>
Sapir, E. (1921). Language. An introduction to the study of speech. Harcourt, Brace and Company.<br>
Sindi, S. S., & Dale, R. (2016). Culturomics as a data playground for tests of selection: Mathematical approaches to detecting selection in word use. Journal of Theoretical Biology, 405, 140–149.<br>
Smith, K., Tamariz, M., & Kirby, S. (2013). Linguistic structure is an evolutionary trade-off between simplicity and expressivity. In Proceedings of Cogsci 2013 (pp. 1348–1353)<br>
Stadler, K., Blythe, R. A., Smith, K., & Kirby, S. (2016). Momentum in Language Change: A Model of Self-Actuating S-shaped Curves. Language Dynamics and Change, 6(2), 171–198.<br>
Steels, L., & Szathmáry, E. (2018). The evolutionary dynamics of language. Biosystems, 164, 128–137.<br>
Stewart, I., & Eisenstein, J. (2018). Making “fetch” happen: The influence of social and linguistic context on nonstandard word growth and decline. Proceedings of the 2018 Conference on Empirical Methods in Natural Language Processing, 4360–4370.<br>
Turney, Peter D. AND Mohammad, S. M. (2019). The natural selection of words: Finding the features of fitness. PLOS ONE, 14(1), 1–20.<br>
Van de Velde, F. (2014). Degeneracy: the maintenance of constructional networks. In The extending scope of construction grammar (Vol. 54, pp. 141–179).<br>
Winter, B., & Wedel, A. (2016). The Co-evolution of Speech and the Lexicon: The Interaction of Functional Pressures, Redundancy, and Category Variation. Topics in Cognitive Science, 8(2), 503–513.<br>
Zhang, M., & Gong, T. (2013). Principles of parametric estimation in modeling language competition. Proceedings of the National Academy of Sciences, 110(24), 9698–9703.<br>
Zipf, G. K. (1949). Human behavior and the principle of least effort: an introduction to human ecology. Addison-Wesley Press.

</font>
